### Gaussian Elimination

**Gaussian Elimination** solves a system of linear equations \\(A\mathbf{x} = \mathbf{b}\\) by transforming the augmented matrix \\([A\,|\,b]\\) into upper-triangular (row echelon) form using elementary row operations, then solving by **back substitution**:
$$
\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} & | & b_1 \\\\ a_{21} & a_{22} & \cdots & a_{2n} & | & b_2 \\\\ \vdots & & \ddots & \vdots & | & \vdots \\\\ a_{n1} & a_{n2} & \cdots & a_{nn} & | & b_n \end{bmatrix} \;\longrightarrow\; \text{upper triangular}
$$

This method is a direct (non-iterative) technique and is the basis of most computational solvers for linear systems, with complexity \\(O(n^3)\\) for an \\(n \times n\\) system. Pivoting (swapping rows) is used to avoid division by zero or numerical instability.


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([
    [2.0, 1.0, -1.0],
    [-3.0, -1.0, 2.0],
    [-2.0, 1.0, 2.0]
])
b = np.array([8.0, -11.0, -3.0])


In [3]:
def gaussian_elimination(A, b):
    A = A.copy()
    b = b.copy()
    n = len(b)

    print("Forward elimination:")
    for k in range(n - 1):
        # Partial pivoting
        max_row = np.argmax(np.abs(A[k:, k])) + k
        if max_row != k:
            A[[k, max_row]] = A[[max_row, k]]
            b[[k, max_row]] = b[[max_row, k]]

        for i in range(k + 1, n):
            factor = A[i, k] / A[k, k]
            A[i, k:] -= factor * A[k, k:]
            b[i] -= factor * b[k]

        print(f"Step {k+1}:")
        print(np.column_stack([A, b]))

    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]

    return x


In [4]:
x = gaussian_elimination(A, b)
print("\nSolution:")
for i, xi in enumerate(x):
    print(f"x{i+1} = {xi:.6f}")

print("\nVerification (A @ x):", A @ x)
print("b:                    ", b)


Forward elimination:
Step 1:
[[ -3.          -1.           2.         -11.        ]
 [  0.           0.33333333   0.33333333   0.66666667]
 [  0.           1.66666667   0.66666667   4.33333333]]
Step 2:
[[ -3.          -1.           2.         -11.        ]
 [  0.           1.66666667   0.66666667   4.33333333]
 [  0.           0.           0.2         -0.2       ]]

Solution:
x1 = 2.000000
x2 = 3.000000
x3 = -1.000000

Verification (A @ x): [  8. -11.  -3.]
b:                     [  8. -11.  -3.]


In [5]:
plt.figure(figsize=(12, 7), dpi=120)

# Axes lines (Desmos-style)
plt.axhline(0)
plt.axvline(0)

# Visualize the residual of A@x - b as a bar chart
residual = A @ x - b
labels = [f"eq{i+1}" for i in range(len(residual))]

plt.bar(labels, residual, alpha=0.7)
plt.grid(True, alpha=0.4)
plt.xlabel("Equation", fontsize=12)
plt.ylabel("Residual (A@x - b)", fontsize=12)
plt.title("Gaussian Elimination Solution Residuals", fontsize=14)
plt.show()
